# -*- coding: utf-8 -*-

# Form implementation generated from reading ui2 file 'ui_main.ui2'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from .resource_rc import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(877, 671)
        self.styleSheet = QtWidgets.QWidget(MainWindow)
        self.styleSheet.setEnabled(True)
        self.styleSheet.setMaximumSize(QtCore.QSize(16777211, 16777215))
        self.styleSheet.setStyleSheet("QWidget {\n"
                                      "    color: rgb(221, 221, 221);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*QMenu*/\n"
                                      "QMenu {\n"
                                      "    background-color: rgb(40, 44, 52);\n"
                                      "    border: 1px solid #555555;\n"
                                      "}\n"
                                      "\n"
                                      "QMenu::item {\n"
                                      "    padding: 8px 20px;\n"
                                      "    color: #ffffff;\n"
                                      "}\n"
                                      "\n"
                                      "QMenu::item:selected {\n"
                                      "    background-color: #333333;\n"
                                      "}\n"
                                      "\n"
                                      "QMenu::separator {\n"
                                      "    height: 1px;\n"
                                      "    background-color: #555555;\n"
                                      "    margin: 4px 0px 4px 10px;\n"
                                      "}\n"
                                      "\n"
                                      "QMenu::icon {\n"
                                      "    margin-right: 10px;\n"
                                      "}\n"
                                      "\n"
                                      "/*****/\n"
                                      "/*QToolTip*/\n"
                                      "QToolTip {\n"
                                      "    color: #ffffff;\n"
                                      "    background-color: rgba(33, 37, 43, 180);\n"
                                      "    border: 1px solid rgb(44, 49, 58);\n"
                                      "    background-image: none;\n"
                                      "    background-position: left center;\n"
                                      "    background-repeat: no-repeat;\n"
                                      "    border-left: 2px solid rgb(255, 121, 198);\n"
                                      "    text-align: left;\n"
                                      "    padding-left: 8px;\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*app*/\n"
                                      "#app{\n"
                                      "    background-color: rgb(40, 44, 52);\n"
                                      "    border: 1px solid rgb(44, 49, 58);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*app_left*/\n"
                                      "#app_left{\n"
                                      "    background-color: rgb(33, 37, 43);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*menu*/\n"
                                      "#menu{\n"
                                      "    border-top: 3px solid rgb(44, 49, 58);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*Button_area*/\n"
                                      "#Button_area{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*Button_area.QToolButton*/\n"
                                      "#Button_area .QToolButton {\n"
                                      "    background-repeat: no-repeat;\n"
                                      "    background-color: rgb(37, 41, 48);\n"
                                      "    color: rgb(113, 126, 149);\n"
                                      "}\n"
                                      "#Button_area .QToolButton:hover {\n"
                                      "    background-color: rgb(40, 44, 52);\n"
                                      "}\n"
                                      "#Button_area .QToolButton:pressed {\n"
                                      "    background-color: rgb(189, 147, 249);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*control_area*/\n"
                                      "#control_area{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*control_area.QToolButton*/\n"
                                      "#control_area .QToolButton {\n"
                                      "    background-repeat: no-repeat;\n"
                                      "    background-color: rgb(37, 41, 48);\n"
                                      "    color: rgb(113, 126, 149);\n"
                                      "}\n"
                                      "#control_area .QToolButton:hover {\n"
                                      "    background-color: rgb(40, 44, 52);\n"
                                      "}\n"
                                      "#control_area .QToolButton:pressed {\n"
                                      "    background-color: rgb(189, 147, 249);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*topic_area*/\n"
                                      "#topic_area{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*logo*/\n"
                                      "#logo{\n"
                                      "    background-color: rgb(40, 44, 52);\n"
                                      "    background-image: url(:/images/images/images/tulip.png);\n"
                                      "    background-position: center;\n"
                                      "    background-repeat:no-repeat;\n"
                                      "    background-size: contain;\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*app_left*/\n"
                                      "#app_right{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*contentBox*/\n"
                                      "#contentBox{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*content_bellow*/\n"
                                      "#content_bellow{\n"
                                      "    background-color: rgb(33, 37, 43);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*bellow_left*/\n"
                                      "#bellow_left{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*signature_office*/\n"
                                      "#signature_office{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*bellow_right*/\n"
                                      "#bellow_right{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*content_top*/\n"
                                      "#content_top{\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*main_area*/\n"
                                      "#main_area{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*widget_changed*/\n"
                                      "#widget_changed{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*widget_changed.QWidget*/\n"
                                      "#widget_changed.QWidget\n"
                                      "{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*select_widget*/\n"
                                      "#select_widget\n"
                                      "{\n"
                                      "    background-color: rgb(33, 37, 43);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*select_area*/\n"
                                      "#select_area\n"
                                      "{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*select_area.QPushButton*/\n"
                                      "#select_area .QPushButton{\n"
                                      "    background-color: rgba(255, 255, 255, 0);\n"
                                      "    border: none;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "#select_area .QPushButton:hover{\n"
                                      "    background-color: rgb(44, 49, 57);\n"
                                      "    border-style: solid;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "#select_area .QPushButton:pressed{\n"
                                      "    background-color: rgb(23, 26, 30);\n"
                                      "    border-style: solid;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*top_menu*/\n"
                                      "#top_menu{\n"
                                      "    background-color: rgb(33, 37, 43);\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*basic_area*/\n"
                                      "#basic_area{\n"
                                      "\n"
                                      "}\n"
                                      "/*****/\n"
                                      "/*basic_area.QPushButton*/\n"
                                      "#basic_area .QPushButton {\n"
                                      "    background-color: rgba(255, 255, 255, 0);\n"
                                      "    border: none;\n"
                                      "    border-radius: 5px;\n"
                                      "}\n"
                                      "#basic_area .QPushButton:hover {\n"
                                      "    background-color: rgb(44, 49, 57);\n"
                                      "    border-style: solid;\n"
                                      "    border-radius: 4px;\n"
                                      "}\n"
                                      "#basic_area .QPushButton:pressed {\n"
                                      "    background-color: rgb(23, 26, 30);\n"
                                      "    border-style: solid;\n"
                                      "    border-radius: 4px;\n"
                                      "}")
        self.styleSheet.setObjectName("styleSheet")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.styleSheet)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.app = QtWidgets.QFrame(self.styleSheet)
        self.app.setMinimumSize(QtCore.QSize(0, 671))
        self.app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app.setObjectName("app")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.app)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.app_left = QtWidgets.QFrame(self.app)
        self.app_left.setMinimumSize(QtCore.QSize(61, 0))
        self.app_left.setMaximumSize(QtCore.QSize(61, 16777215))
        self.app_left.setSizeIncrement(QtCore.QSize(61, 0))
        self.app_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_left.setObjectName("app_left")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.app_left)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topic_area = QtWidgets.QFrame(self.app_left)
        self.topic_area.setMinimumSize(QtCore.QSize(0, 61))
        self.topic_area.setMaximumSize(QtCore.QSize(16777215, 61))
        self.topic_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topic_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topic_area.setObjectName("topic_area")
        self.logo = QtWidgets.QFrame(self.topic_area)
        self.logo.setGeometry(QtCore.QRect(10, 10, 40, 40))
        self.logo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.logo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.logo.setObjectName("logo")
        self.verticalLayout_3.addWidget(self.topic_area)
        self.menu = QtWidgets.QFrame(self.app_left)
        self.menu.setMinimumSize(QtCore.QSize(0, 0))
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.menu)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.control_area = QtWidgets.QFrame(self.menu)
        self.control_area.setMinimumSize(QtCore.QSize(0, 51))
        self.control_area.setMaximumSize(QtCore.QSize(16777215, 51))
        self.control_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.control_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.control_area.setObjectName("control_area")
        self.setup_button = QtWidgets.QToolButton(self.control_area)
        self.setup_button.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.setup_button.setStyleSheet("")
        self.setup_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/ei.align-justify.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.setup_button.setIcon(icon)
        self.setup_button.setObjectName("setup_button")
        self.verticalLayout_4.addWidget(self.control_area)
        self.Button_area = QtWidgets.QFrame(self.menu)
        self.Button_area.setMinimumSize(QtCore.QSize(0, 181))
        self.Button_area.setMaximumSize(QtCore.QSize(16777215, 181))
        self.Button_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Button_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Button_area.setObjectName("Button_area")
        self.socket_create = QtWidgets.QToolButton(self.Button_area)
        self.socket_create.setGeometry(QtCore.QRect(0, 0, 61, 51))
        self.socket_create.setStyleSheet("")
        self.socket_create.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/mdi.bluetooth-connect.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.socket_create.setIcon(icon1)
        self.socket_create.setObjectName("socket_create")
        self.tensor_create = QtWidgets.QToolButton(self.Button_area)
        self.tensor_create.setGeometry(QtCore.QRect(0, 60, 61, 51))
        self.tensor_create.setText("")
        self.tensor_create.setObjectName("tensor_create")
        self.other_create = QtWidgets.QToolButton(self.Button_area)
        self.other_create.setGeometry(QtCore.QRect(0, 120, 61, 51))
        self.other_create.setText("")
        self.other_create.setObjectName("other_create")
        self.verticalLayout_4.addWidget(self.Button_area)
        self.other_area = QtWidgets.QFrame(self.menu)
        self.other_area.setMinimumSize(QtCore.QSize(0, 100))
        self.other_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.other_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.other_area.setObjectName("other_area")
        self.verticalLayout_4.addWidget(self.other_area)
        self.verticalLayout_3.addWidget(self.menu)
        self.horizontalLayout_2.addWidget(self.app_left)
        self.app_right = QtWidgets.QFrame(self.app)
        self.app_right.setMinimumSize(QtCore.QSize(814, 0))
        self.app_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_right.setObjectName("app_right")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.app_right)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.top_menu = QtWidgets.QFrame(self.app_right)
        self.top_menu.setMinimumSize(QtCore.QSize(0, 61))
        self.top_menu.setMaximumSize(QtCore.QSize(16777215, 61))
        self.top_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.top_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.top_menu.setObjectName("top_menu")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.top_menu)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.other_area_3 = QtWidgets.QFrame(self.top_menu)
        self.other_area_3.setMinimumSize(QtCore.QSize(611, 0))
        self.other_area_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.other_area_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.other_area_3.setObjectName("other_area_3")
        self.name = QtWidgets.QLabel(self.other_area_3)
        self.name.setGeometry(QtCore.QRect(0, 4, 551, 51))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.horizontalLayout_3.addWidget(self.other_area_3)
        self.basic_area = QtWidgets.QFrame(self.top_menu)
        self.basic_area.setMinimumSize(QtCore.QSize(204, 0))
        self.basic_area.setMaximumSize(QtCore.QSize(204, 16777215))
        self.basic_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.basic_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.basic_area.setObjectName("basic_area")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.basic_area)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.minimize = QtWidgets.QPushButton(self.basic_area)
        self.minimize.setMinimumSize(QtCore.QSize(60, 30))
        self.minimize.setMaximumSize(QtCore.QSize(60, 31))
        self.minimize.setStyleSheet("")
        self.minimize.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/msc.chrome-minimize.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.minimize.setIcon(icon2)
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_4.addWidget(self.minimize)
        self.magnify = QtWidgets.QPushButton(self.basic_area)
        self.magnify.setMinimumSize(QtCore.QSize(60, 30))
        self.magnify.setMaximumSize(QtCore.QSize(60, 30))
        self.magnify.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/mdi.square-outline.png"), QtGui.QIcon.Normal,
                        QtGui.QIcon.Off)
        self.magnify.setIcon(icon3)
        self.magnify.setObjectName("magnify")
        self.horizontalLayout_4.addWidget(self.magnify)
        self.close = QtWidgets.QPushButton(self.basic_area)
        self.close.setMinimumSize(QtCore.QSize(60, 30))
        self.close.setMaximumSize(QtCore.QSize(60, 30))
        self.close.setStyleSheet("")
        self.close.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/mdi.close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon4)
        self.close.setObjectName("close")
        self.horizontalLayout_4.addWidget(self.close)
        self.horizontalLayout_3.addWidget(self.basic_area)
        self.verticalLayout.addWidget(self.top_menu)
        self.contentBox = QtWidgets.QFrame(self.app_right)
        self.contentBox.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentBox.setLineWidth(0)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.content_top = QtWidgets.QFrame(self.contentBox)
        self.content_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_top.setObjectName("content_top")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.content_top)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.select_widget = QtWidgets.QFrame(self.content_top)
        self.select_widget.setMinimumSize(QtCore.QSize(0, 31))
        self.select_widget.setMaximumSize(QtCore.QSize(16777215, 31))
        self.select_widget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_widget.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_widget.setObjectName("select_widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.select_widget)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.other_area_2 = QtWidgets.QFrame(self.select_widget)
        self.other_area_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.other_area_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.other_area_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.other_area_2.setObjectName("other_area_2")
        self.horizontalLayout_6.addWidget(self.other_area_2)
        self.select_area = QtWidgets.QFrame(self.select_widget)
        self.select_area.setMinimumSize(QtCore.QSize(331, 0))
        self.select_area.setMaximumSize(QtCore.QSize(331, 16777215))
        self.select_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.select_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.select_area.setObjectName("select_area")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.select_area)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.home_button = QtWidgets.QPushButton(self.select_area)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setBold(False)
        font.setWeight(50)
        self.home_button.setFont(font)
        self.home_button.setStyleSheet("")
        self.home_button.setObjectName("home_button")
        self.horizontalLayout_7.addWidget(self.home_button)
        self.socket_button = QtWidgets.QPushButton(self.select_area)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        self.socket_button.setFont(font)
        self.socket_button.setObjectName("socket_button")
        self.horizontalLayout_7.addWidget(self.socket_button)
        self.tensor_button = QtWidgets.QPushButton(self.select_area)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        self.tensor_button.setFont(font)
        self.tensor_button.setObjectName("tensor_button")
        self.horizontalLayout_7.addWidget(self.tensor_button)
        self.horizontalLayout_6.addWidget(self.select_area)
        self.verticalLayout_5.addWidget(self.select_widget)
        self.main_area = QtWidgets.QFrame(self.content_top)
        self.main_area.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.main_area.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_area.setObjectName("main_area")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.main_area)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.widget_changed = QtWidgets.QStackedWidget(self.main_area)
        self.widget_changed.setMinimumSize(QtCore.QSize(60, 30))
        self.widget_changed.setStyleSheet("background: transparent;")
        self.widget_changed.setObjectName("widget_changed")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background:url(:/images/images/images/tulip.theme.png);\n"
                                "background-position: center;\n"
                                "background-repeat: no-repeat;\n"
                                "background-color:transparent;")
        self.home.setObjectName("home")
        self.widget_changed.addWidget(self.home)
        self.socket = QtWidgets.QWidget()
        self.socket.setObjectName("socket")
        self.widget_changed.addWidget(self.socket)
        self.tensor = QtWidgets.QWidget()
        self.tensor.setObjectName("tensor")
        self.widget_changed.addWidget(self.tensor)
        self.verticalLayout_6.addWidget(self.widget_changed)
        self.verticalLayout_5.addWidget(self.main_area)
        self.verticalLayout_2.addWidget(self.content_top)
        self.content_bellow = QtWidgets.QFrame(self.contentBox)
        self.content_bellow.setMinimumSize(QtCore.QSize(0, 20))
        self.content_bellow.setMaximumSize(QtCore.QSize(16777215, 20))
        self.content_bellow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.content_bellow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.content_bellow.setObjectName("content_bellow")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.content_bellow)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bellow_left = QtWidgets.QFrame(self.content_bellow)
        self.bellow_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bellow_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bellow_left.setObjectName("bellow_left")
        self.horizontalLayout_5.addWidget(self.bellow_left)
        self.bellow_right = QtWidgets.QFrame(self.content_bellow)
        self.bellow_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bellow_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bellow_right.setObjectName("bellow_right")
        self.label = QtWidgets.QLabel(self.bellow_right)
        self.label.setGeometry(QtCore.QRect(11, -1, 391, 21))
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.bellow_right)
        self.verticalLayout_2.addWidget(self.content_bellow)
        self.verticalLayout.addWidget(self.contentBox)
        self.horizontalLayout_2.addWidget(self.app_right)
        self.horizontalLayout.addWidget(self.app)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.widget_changed.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Tulip Dream——from the Tulip Family"))
        self.home_button.setText(_translate("MainWindow", "home"))
        self.socket_button.setText(_translate("MainWindow", "socket"))
        self.tensor_button.setText(_translate("MainWindow", "tensor"))
        self.label.setText(_translate("MainWindow", "                               created by sjeozq"))


