# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtGui, QtWidgets
from .resource_rc import *


class Ui_socket(object):
    def setupUi(self, socket):
        socket.setObjectName("socket")
        socket.resize(241, 274)
        socket.setMinimumSize(QtCore.QSize(241, 274))
        socket.setMaximumSize(QtCore.QSize(241, 274))
        socket.setStyleSheet("#app{\n"
                             "    background-color: rgb(40, 44, 52);\n"
                             "    color:white;\n"
                             "}\n"
                             "#app .QPushButton {\n"
                             "    background-color: ;\n"
                             "    border: none;\n"
                             "    border-radius: 5px;\n"
                             "}\n"
                             "#app .QPushButton:hover {\n"
                             "    background-color: rgb(44, 49, 57);\n"
                             "    border-style: solid;\n"
                             "    border-radius: 4px;\n"
                             "}\n"
                             "#app .QPushButton:pressed {\n"
                             "    background-color: rgb(23, 26, 30);\n"
                             "    border-style: solid;\n"
                             "    border-radius: 4px;\n"
                             "}\n"
                             "\n"
                             "\n"
                             "")
        self.verticalLayout = QtWidgets.QVBoxLayout(socket)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.app = QtWidgets.QFrame(socket)
        self.app.setStyleSheet("color:white;")
        self.app.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app.setObjectName("app")
        self.app_top = QtWidgets.QFrame(self.app)
        self.app_top.setGeometry(QtCore.QRect(0, 0, 241, 31))
        self.app_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_top.setObjectName("app_top")
        self.close = QtWidgets.QPushButton(self.app_top)
        self.close.setGeometry(QtCore.QRect(200, 0, 41, 31))
        self.close.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/mdi.close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.close.setIcon(icon)
        self.close.setObjectName("close")
        self.app_bellow = QtWidgets.QFrame(self.app)
        self.app_bellow.setGeometry(QtCore.QRect(0, 31, 241, 245))
        self.app_bellow.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.app_bellow.setFrameShadow(QtWidgets.QFrame.Raised)
        self.app_bellow.setObjectName("app_bellow")
        self.label = QtWidgets.QLabel(self.app_bellow)
        self.label.setGeometry(QtCore.QRect(10, 50, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.app_bellow)
        self.label_2.setGeometry(QtCore.QRect(10, 90, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.app_bellow)
        self.label_3.setGeometry(QtCore.QRect(10, 130, 72, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.app_bellow)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 72, 21))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.app_bellow)
        self.label_5.setGeometry(QtCore.QRect(10, 10, 72, 20))
        self.label_5.setObjectName("label_5")
        self.cancel = QtWidgets.QPushButton(self.app_bellow)
        self.cancel.setGeometry(QtCore.QRect(130, 210, 61, 28))
        self.cancel.setObjectName("cancel")
        self.create = QtWidgets.QPushButton(self.app_bellow)
        self.create.setGeometry(QtCore.QRect(40, 210, 61, 28))
        self.create.setObjectName("create")
        self.socket_way = QtWidgets.QComboBox(self.app_bellow)
        self.socket_way.setGeometry(QtCore.QRect(120, 10, 113, 21))
        self.socket_way.setStyleSheet("border:1px solid white")
        self.socket_way.setObjectName("socket_way")
        self.Host_name = QtWidgets.QLineEdit(self.app_bellow)
        self.Host_name.setGeometry(QtCore.QRect(120, 50, 113, 21))
        self.Host_name.setObjectName("Host_name")
        self.client_name = QtWidgets.QLineEdit(self.app_bellow)
        self.client_name.setGeometry(QtCore.QRect(120, 90, 113, 21))
        self.client_name.setObjectName("client_name")
        self.Port = QtWidgets.QLineEdit(self.app_bellow)
        self.Port.setGeometry(QtCore.QRect(120, 130, 113, 21))
        self.Port.setObjectName("Port")
        self.socket_name = QtWidgets.QLineEdit(self.app_bellow)
        self.socket_name.setGeometry(QtCore.QRect(120, 170, 113, 21))
        self.socket_name.setObjectName("socket_name")
        self.verticalLayout.addWidget(self.app)

        self.retranslateUi(socket)
        QtCore.QMetaObject.connectSlotsByName(socket)

    def retranslateUi(self, socket):
        _translate = QtCore.QCoreApplication.translate
        socket.setWindowTitle(_translate("socket", "Form"))
        self.label.setText(_translate("socket", "主机名称"))
        self.label_2.setText(_translate("socket", "客户端名称"))
        self.label_3.setText(_translate("socket", "端口号"))
        self.label_4.setText(_translate("socket", "通信名称"))
        self.label_5.setText(_translate("socket", "通信方式"))
        self.cancel.setText(_translate("socket", "Cancel"))
        self.create.setText(_translate("socket", "Submit"))
